name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  make-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run make all
        run: make all

      - name: Run make test
        run: make test-verbose
